"""initial schema

Revision ID: 77cd0813f4b6
Revises: 
Create Date: 2026-04-22 23:53:04.769689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cd0813f4b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('local_title', sa.String(length=255), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', name='uq_owner_type_owner_id')
    )
    op.create_index(op.f('ix_owner_owner_id'), 'owner', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_owner_type'), 'owner', ['owner_type'], unique=False)
    op.create_table('prompt_preset',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('discipline', sa.String(length=64), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('source_preset_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_preset_id'], ['prompt_preset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_preset_scope'), 'prompt_preset', ['scope'], unique=False)
    op.create_table('image_item',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_final_version_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_item_current_final_version_id'), 'image_item', ['current_final_version_id'], unique=False)
    op.create_index(op.f('ix_image_item_owner_id'), 'image_item', ['owner_id'], unique=False)
    op.create_table('image_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('image_item_id', sa.String(length=32), nullable=False),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True),
    sa.Column('origin_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=128), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('prompt_summary', sa.String(length=255), nullable=True),
    sa.Column('mask_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_item_id'], ['image_item.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['image_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_version_image_item_id'), 'image_version', ['image_item_id'], unique=False)
    op.create_index(op.f('ix_image_version_parent_version_id'), 'image_version', ['parent_version_id'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('image_item_id', sa.String(length=32), nullable=True),
    sa.Column('version_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_item_id'], ['image_item.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['image_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_created_at'), 'event_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_image_item_id'), 'event_log', ['image_item_id'], unique=False)
    op.create_index(op.f('ix_event_log_owner_id'), 'event_log', ['owner_id'], unique=False)
    op.create_index(op.f('ix_event_log_version_id'), 'event_log', ['version_id'], unique=False)
    op.create_table('image_mask',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('image_item_id', sa.String(length=32), nullable=False),
    sa.Column('base_version_id', sa.String(length=32), nullable=False),
    sa.Column('mask_type', sa.String(length=16), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['image_version.id'], ),
    sa.ForeignKeyConstraint(['image_item_id'], ['image_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_mask_base_version_id'), 'image_mask', ['base_version_id'], unique=False)
    op.create_index(op.f('ix_image_mask_image_item_id'), 'image_mask', ['image_item_id'], unique=False)
    op.create_table('publish_record',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('publish_scope', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('image_item_id', sa.String(length=32), nullable=True),
    sa.Column('version_id', sa.String(length=32), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_item_id'], ['image_item.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['image_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_record_owner_id'), 'publish_record', ['owner_id'], unique=False)
    op.create_table('edit_job',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('image_item_id', sa.String(length=32), nullable=False),
    sa.Column('base_version_id', sa.String(length=32), nullable=True),
    sa.Column('output_version_id', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('normalized_prompt', sa.Text(), nullable=False),
    sa.Column('mask_id', sa.String(length=32), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['image_version.id'], ),
    sa.ForeignKeyConstraint(['image_item_id'], ['image_item.id'], ),
    sa.ForeignKeyConstraint(['mask_id'], ['image_mask.id'], ),
    sa.ForeignKeyConstraint(['output_version_id'], ['image_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_job_base_version_id'), 'edit_job', ['base_version_id'], unique=False)
    op.create_index(op.f('ix_edit_job_image_item_id'), 'edit_job', ['image_item_id'], unique=False)
    op.create_index(op.f('ix_edit_job_output_version_id'), 'edit_job', ['output_version_id'], unique=False)
    op.create_index(op.f('ix_edit_job_owner_id'), 'edit_job', ['owner_id'], unique=False)
    op.create_index(op.f('ix_edit_job_status'), 'edit_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_job_status'), table_name='edit_job')
    op.drop_index(op.f('ix_edit_job_owner_id'), table_name='edit_job')
    op.drop_index(op.f('ix_edit_job_output_version_id'), table_name='edit_job')
    op.drop_index(op.f('ix_edit_job_image_item_id'), table_name='edit_job')
    op.drop_index(op.f('ix_edit_job_base_version_id'), table_name='edit_job')
    op.drop_table('edit_job')
    op.drop_index(op.f('ix_publish_record_owner_id'), table_name='publish_record')
    op.drop_table('publish_record')
    op.drop_index(op.f('ix_image_mask_image_item_id'), table_name='image_mask')
    op.drop_index(op.f('ix_image_mask_base_version_id'), table_name='image_mask')
    op.drop_table('image_mask')
    op.drop_index(op.f('ix_event_log_version_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_owner_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_image_item_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_created_at'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_image_version_parent_version_id'), table_name='image_version')
    op.drop_index(op.f('ix_image_version_image_item_id'), table_name='image_version')
    op.drop_table('image_version')
    op.drop_index(op.f('ix_image_item_owner_id'), table_name='image_item')
    op.drop_index(op.f('ix_image_item_current_final_version_id'), table_name='image_item')
    op.drop_table('image_item')
    op.drop_index(op.f('ix_prompt_preset_scope'), table_name='prompt_preset')
    op.drop_table('prompt_preset')
    op.drop_index(op.f('ix_owner_owner_type'), table_name='owner')
    op.drop_index(op.f('ix_owner_owner_id'), table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
